### ISSUE TITLE
pdf links error?.

### ISSUE THREAD

**Issue by huaifeng1993** [QianyiWu/objectsdf_plus#1]
can't find where to download the pdf.if the links provided in readme correct?

**Comment by QianyiWu** [comment]
Hi, thanks for your interest. I am preparing the camera-ready version of this paper. Will back to you in this thread once it is done.

**Comment by QianyiWu** [comment]
Hi, the arxiv link of ObjectSDF++ is given [here](https://arxiv.org/abs/2308.07868).
