### ISSUE TITLE
Question about preprocessing Scannet

### ISSUE THREAD

**Issue by Pixie8888** [QianyiWu/objectsdf_plus#12]
Dear author,

I have a question about preprocessing scannet data in preprocee/scannet_to_objsdfpp.py:
Based on my understanding, it tries to normalize a scene to unit cude with center at origin, and the ```scale_mat``` is the transformation of the unit cube to the original scene. But why ```scale_mat[:3, 3] = -center```. I think it should be ```scale_mat[:3, 3] =+ center```. Please help me clarify this. Thanks!
<img width="444" alt="image" src="https://github.com/QianyiWu/objectsdf_plus/assets/72333326/72162201-6f3a-45cf-84e2-0d9e504625ee">

**Comment by QianyiWu** [comment]
Hi,

I think you can understand it in this way:
before line 152, the scale_mat would be a matrix with 
```
[s1,   0 ,  0, -s1*t1,
   0, s2,   0, -s2*t2,
   0,   0, s3, -s3*t3,
   0,   0,   0, 1]
```

Its inverse matrix is (the real scale_mat used in calculation).
```
[1/s1,   0 ,  0, t1,
   0, 1/s2,   0, t2,
   0,   0, 1/s3, t3,
   0,   0,   0, 1]
```
The physical meaning of this scale_mat can be understand as a conversion from a 3D point in ```[-1,1]^3``` to the world coordinates centered at ```[t1,t2,t3]```. Therefore, it can be used to normalize everything into a unit cube if you play with the scale parameters and center.

**Comment by Pixie8888** [comment]
thanks for your explanation!
