### ISSUE TITLE
Train/Test Split in Replica Dataset

### ISSUE THREAD

**Issue by RemiChierchia** [QianyiWu/objectsdf_plus#14]
Dear authors, thank you for the amazing job!

I was wondering if you define a train/test split or if you train for all the 100 images in the Replica dataset (I understand that you use the dataset used in MonoSDF plus the instance segmentation masks with classes re-defined).

I've looked at MonoSDF but I couldn't find any specifications either.

Could you provide some more details on that matter?

Thank you!
Remi

**Comment by QianyiWu** [comment]
Hi,

As the target of this project is surface reconstruction, we used all 100 images to get the final surface. Here is the code to get dataset by the ``get_class`` function [here](https://github.com/QianyiWu/objectsdf_plus/blob/4c93f016d553ed3251a527ef1a32821cf53af90c/code/training/objectsdfplus_train.py#L85-L92). It will import the dataset definition in [here](https://github.com/QianyiWu/objectsdf_plus/blob/main/code/datasets/scene_dataset.py), same as in MonoSDF [here](https://github.com/autonomousvision/monosdf/blob/main/code/datasets/scene_dataset.py).

**Comment by RemiChierchia** [comment]
Thank you!
