### ISSUE TITLE
Could you please release the reconstructed 3D meshes

### ISSUE THREAD

**Issue by Runsong123** [QianyiWu/objectsdf_plus#2]
Thanks for the great work and the open-source code!

Could you please release the reconstructed 3D meshes for objects in the scannet scenes and replica dataset? 
It would be more convenient to follow your work and compare with objectsdf-plus.
Many thanks in advance!

Best regards
Runsong

**Comment by Runsong123** [comment]
Got it. Thanks.

**Comment by RemiChierchia** [comment]
Hi, thank you for releasing the reconstructed surfaces! 

I have a further question related to this issue.
I noticed, for example, for scan1 that you should have 46 classes and 46 surfaces. 
I also noticed that in the evaluation you picked those meshes as the "valid" ones. 
I tried to have a look in the code but I could not find if you introduced a way to get rid of "invalid" reconstructions. 
Could you comment on that? Is the evaluation performed on the surface classes you provided or on all 46 classes?

Also, another question about the class remapping file. I saw that `replica_to_objsdfpp.py` outputs this file. I ran again the script on a recently downloaded version of the vmap processed data and for example, from scene1 the class 45 is mapped to instance class 91, while in your provided data the same class is mapped to the background. Could you clarify how you compute this remapping?

Thank you,
Remi
