### ISSUE TITLE
Why you use 'get_surface_trace' for marching cubes in plots.py instead of 'get_surface_sliding' like MonoSDF

### ISSUE THREAD

**Issue by DaLi-Jack** [QianyiWu/objectsdf_plus#6]
Hi, Congrats for your great work!
I have a very detailed question.
I noticed that your code refers to the MonoSDF code,
but you use '[get_surface_trace](https://github.com/QianyiWu/objectsdf_plus/blob/98e84ebc9f6ca68d711fdedb6e9f8a279c79bc98/code/utils/plots.py#L66)' for marching cubes in plots.py instead of '[get_surface_sliding](https://github.com/autonomousvision/monosdf/blob/12513009cd20a08b35ddc2c55a7e42da2c7baf43/code/utils/plots.py#L36)' like MonoSDF.
Could you let me know if there is any special reason for doing this? 
I would be grateful for any help you can provide!

**Comment by QianyiWu** [comment]
Hi,

This function inherited from [ObjectSDF](https://github.com/QianyiWu/objsdf/blob/9ddb7106c35d4603453992978031c8f2dbb5737e/code/utils/plots.py#L51C14-L51C14). I found the 'get_surface_sliding' including some additional operations like building point pyramids for marching cube while 'get_surface_trace' is much more like original marching cube.

**Comment by DaLi-Jack** [comment]
I see! Thank you very much for your patient answer!
In addition to being more like the original marching cube, will 'get_surface_trace' get a **better mesh**, such as smoother?
Because I found that 'get_surface_sliding' **seems** to be faster and uses less GPU memory.

**Comment by QianyiWu** [comment]
From my understanding, the motivation of the point pyramid is to reduce some unnecessary computations from the coarse level to the fine level by applying the mask. It should be a faster version and consume less GPU memory. 

I also agree that the original marching cube might produce a smoother surface when we combine multiple object SDFs. The scene SDF produced by applying minimum operation on all object SDFs is **an approximation** of true scene SDF, especially in the inner part. A dense sampling for marching cubes could alleviate some missing computation.

**Comment by DaLi-Jack** [comment]
okk! Thank you very much for your patient answer!
