### ISSUE TITLE
Distributed training error multiple terminals 

### ISSUE THREAD

**Issue by wuyingxiong** [QianyiWu/objectsdf_plus#8]
Thanks for your great work!

I want to train multiple instances concurrently in different terminals ,using the commands  following.

terminal 1:CUDA_VISIBLE_DEVICES=1 torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 training/exp_runner.py --conf confs/replica_objsdfplus.conf --scan_id 4

terminal 2:CUDA_VISIBLE_DEVICES=2 torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 training/exp_runner.py --conf confs/replica_objsdfplus.conf --scan_id 5

I also change the local_rank value.But it still has port error.

RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

How can I correct the code ?

**Comment by QianyiWu** [comment]
You can try to specify a new master port for each experiment (e.g. 60004& 60005): 

CUDA_VISIBLE_DEVICES=1 torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 **--master_port=60004** training/exp_runner.py --conf confs/replica_objsdfplus.conf --scan_id 4

CUDA_VISIBLE_DEVICES=2 torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 **--master_port=60005** training/exp_runner.py --conf confs/replica_objsdfplus.conf --scan_id 5

**Comment by wuyingxiong** [comment]
Thanks for your quick reply，I will try later.
